Type hints
dem1tris/intellij-rust pull request #2
Opened 2018-08-07 12:52 UTC by dem1tris

2018-08-20 08:02 UTC, sirgl requested changes

2018-08-20 08:02 UTC, sirgl commented on src/test/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandlerTest.kt
> +    /*fun testFnNoArgs() = checkByText("""
Нужно больше тестов. Кроме того, удобнее использовать // ^ для обозначения каретки. В этом случае будет доступна подсветка синтаксиса в данном фрагменте текста (а caret - это невалидный синтаксис). Можно посмотреть пример таких тестов в RsGenericExpressionTypeInferenceTest

2018-08-20 08:02 UTC, sirgl commented on src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
> +        if (declaredSized) return@associate Pair(param, false)
Возможно, стоит заменить на `to`

2018-08-20 08:02 UTC, sirgl commented on src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
> +        val derivedSized = param.bounds
Не уверен, что обработка Sized должна быть здесь. Вероятно, стоит вынести это куда-то в lang пакет. Кроме того, это изменение должно быть отдельным PR с особым вниманием для ревью, потому что это часть поддержки языка

2018-08-20 08:02 UTC, sirgl commented on src/test/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandlerTest.kt
> +    /*fun testFnNoArgs() = checkByText("""
Кроме того, стоит проверить, как это все работает с некорректными типами. Например, <> есть в определении, но типовой параметр отсутствует.

2018-08-20 09:40 UTC, dem1tris commented on src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
> +        val derivedSized = param.bounds
Значит, так мы и сделаем :D 
Тут оказалось, что почти такой же велосипед изобрели до меня. Я его даже видел, но он мне не понравился тогда. И неспроста.
File: ext/RsTypeParameter.kt
```kotlin
val RsTypeParameter.isSized: Boolean get() {
    val stub = stub
    if (stub != null) return stub.isSized

    // We can't use `resolve` here to find `?Sized` bound because it causes `IndexNotReadyException` while indexing.
    // Instead of it we just check `?` before trait name in bound
    // because at this moment only `Sized` trait can have `?` modifier
    val owner = parent?.parent as? RsGenericDeclaration
    val whereBounds =
        owner?.whereClause?.wherePredList.orEmpty()
            .filter { (it.typeReference?.typeElement as? RsBaseType)?.name == name }
            .flatMap { it.typeParamBounds?.polyboundList.orEmpty() }
    val bounds = typeParamBounds?.polyboundList.orEmpty() + whereBounds
    return bounds.none { it.q != null }
}
```
Здесь я слабо понимаю, что есть stub, вижу какой-то костыль, иначе во время индексирования исключение, и вижу, что они просто говорят, что если нигде нет `?`, то `Sized`. Но фокус в том, что явный `Sized` побеждает `?Sized`, судя по тому, как компилятор на это реагирует. И для этого дополнительно нужно просмотреть все супертрейты на предмет `Sized`, что я и делаю.

Мало того, сейчас я заменил это на свою реализацию, и false-positive инспекция перестала врать в случае `?Sized + Clone`, например. Вот эта: https://github.com/intellij-rust/intellij-rust/issues/2530

2018-08-27 03:14 UTC, sirgl commented on src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
> +            // todo: understand
final code must contains no such todos

2018-08-27 03:15 UTC, sirgl commented
In general looks ok, remove misleading todos, close this PR and make real PR in intellij-rust repo.

2018-08-27 03:16 UTC, sirgl commented on src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
> +    override fun getParametersForLookup(item: LookupElement?, context: ParameterInfoContext?): Array<Any>? = null
By the way, why are you not filling completion items?

2018-09-08 07:09 UTC, merged